name: Our CI
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install .[test]
      - name: Run test
      - run: python -m pytest
      
