name: Our CI
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]
        include:
          - os: macos-14
            python-version: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
            
      - name: Install markdown slides
        run: pip install git+https://gitlab.com/da_doomer/markdown-slides.git
      - name: Generate slides
        run: mdslides slides.md --output_dir slides